'use client';
import { useEffect, useState } from 'react';
import { apiFetch } from '@/lib/apiFetch';
type Citation = { materialId: string; filename: string; page: number | null; snippet: string };
type ChatMessage = { role: 'USER' | 'ASSISTANT'; content: string; grounded?: boolean; citations?: Citation[] };
export default function TutorTab({ projectId }: { projectId: string }) {
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [conversationId, setConversationId] = useState<string>(); const [question, setQuestion] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { apiFetch<{ conversations: { id: string; messages: ChatMessage[] }[] }>(`/api/projects/${projectId}/tutor`).then((data) => { const latest = data.conversations[0]; if (latest) { setConversationId(latest.id); setMessages(latest.messages); } }).catch((err) => setError(err.message)); }, [projectId]);
  async function ask(event: React.FormEvent) { event.preventDefault(); if (!question.trim()) return; const userMessage = { role: 'USER' as const, content: question }; setMessages((current) => [...current, userMessage]); setQuestion(''); setLoading(true); setError(null); try { const data = await apiFetch<{ conversationId: string; message: ChatMessage }>(`/api/projects/${projectId}/tutor`, { method: 'POST', body: JSON.stringify({ question: userMessage.content, conversationId }) }); setConversationId(data.conversationId); setMessages((current) => [...current, data.message]); } catch (err) { setMessages((current) => current.slice(0, -1)); setError(err instanceof Error ? err.message : 'The Tutor could not answer right now.'); } finally { setLoading(false); } }
  return <div className="surface overflow-hidden flex flex-col h-[65vh]"><div className="px-5 py-4 border-b bg-slate-50/80 flex items-center justify-between"><div><p className="font-semibold text-sm">AI Tutor</p><p className="text-xs text-slate-500 mt-0.5">Grounded in this project&apos;s materials</p></div><span className="text-xs font-semibold text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded-full">Evidence first</span></div><div className="flex-1 overflow-y-auto space-y-5 p-5 sm:p-7">{error && <p className="text-sm text-red-600">{error}</p>}{messages.length === 0 && <div className="max-w-lg"><p className="eyebrow">Ready when you are</p><h3 className="font-semibold text-lg mt-1">What would you like to understand?</h3><p className="text-sm text-slate-500 mt-2">Ask about your material, request a simpler explanation, or test your understanding. I&apos;ll cite the material I use—and say so when it doesn&apos;t contain the answer.</p></div>}{messages.map((message, index) => <div key={index} className={`max-w-[88%] ${message.role === 'USER' ? 'ml-auto' : ''}`}><div className="text-[11px] font-bold uppercase tracking-wider mb-1.5 text-slate-400">{message.role === 'USER' ? 'You' : message.grounded === false ? 'Tutor · evidence check' : 'Tutor'}</div><div className={`rounded-2xl px-4 py-3.5 text-sm leading-6 ${message.role === 'USER' ? 'bg-brand-600 text-white shadow-sm' : message.grounded === false ? 'bg-amber-50 border border-amber-200 text-amber-950' : 'bg-slate-50 border border-slate-100'}`}>{message.content}</div>{message.citations?.length ? <div className="mt-2 space-y-1 rounded-xl bg-brand-50/70 px-3 py-2">{message.citations.map((citation, itemIndex) => <p key={itemIndex} className="text-xs text-slate-500">↗ Source: {citation.filename}{citation.page ? ` — Page ${citation.page}` : ''}</p>)}</div> : null}{message.role === 'ASSISTANT' && message.grounded === false && <p className="text-xs text-amber-700 mt-2">I couldn&apos;t find enough support in this project&apos;s materials to answer that reliably.</p>}</div>)}{loading && <div className="text-sm text-slate-500 flex gap-2 items-center"><span className="h-2 w-2 rounded-full bg-brand-500 animate-pulse"/>Finding evidence and thinking…</div>}</div><form onSubmit={ask} className="border-t bg-white p-4 flex gap-2"><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask the Tutor a question…" className="form-control flex-1"/><button disabled={loading} className="primary-button">Ask</button></form></div>;
}
